### ISSUE TITLE
graylog2 0.92.3 server can't installed via AMI 

### ISSUE THREAD

**Issue by baldzern4** [Graylog2/graylog2-cookbook#7]
graylog2 Version 0.92.3-1419362218 
AMI used: ami-843e0e99

Error messages after running:
sudo graylog2-ctl reconfigure

```
Recipe: ntp::default
  * apt_package[ntp] action install
================================================================================
    Error executing action `install` on resource 'apt_package[ntp]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '100'
    ---- Begin output of apt-get -q -y install ntp=1:4.2.6.p5+dfsg-3ubuntu2.14.04.1 ----
    STDOUT: Reading package lists...
    Building dependency tree...
    Reading state information...
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     ntp : Depends: libopts25 (>= 1:5.18) but it is not installable
    STDERR: E: Unable to correct problems, you have held broken packages.
    ---- End output of apt-get -q -y install ntp=1:4.2.6.p5+dfsg-3ubuntu2.14.04.1 ----
    Ran apt-get -q -y install ntp=1:4.2.6.p5+dfsg-3ubuntu2.14.04.1 returned 100
```

.
.
.

```
Recipe: graylog2::graylog2-server
  * service[graylog2-server] action restart
    
    ================================================================================
    Error executing action `restart` on resource 'service[graylog2-server]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv -w 45 restart /opt/graylog2/service/graylog2-server ----
    STDOUT: timeout: run: /opt/graylog2/service/graylog2-server: (pid 1619) 74s
    STDERR: 
    ---- End output of /opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv -w 45 restart /opt/graylog2/service/graylog2-server ----
    Ran /opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv -w 45 restart /opt/graylog2/service/graylog2-server returned 1
    
    Resource Declaration:
    ---------------------
    # In /opt/graylog2/embedded/cookbooks/runit/definitions/runit_service.rb
    
    190:     service params[:name] do
    191:       control_cmd = node[:runit][:sv_bin]
    192:       if params[:owner]
    193:         control_cmd = "#{node[:runit][:chpst_bin]} -u #{params[:owner]} #{control_cmd}"
    194:       end
    195:       provider Chef::Provider::Service::Simple
    
    Compiled Resource:
    ------------------
    # Declared in /opt/graylog2/embedded/cookbooks/runit/definitions/runit_service.rb:190:in `block in from_file'
    
    service("graylog2-server") do
      params {:directory=>"/opt/graylog2/sv", :only_if=>false, :finish_script=>false, :control=>["t"], :run_restart=>false, :active_directory=>"/opt/graylog2/service", :init_script_template=>nil, :owner=>"root", :group=>"root", :template_name=>"graylog2-server", :start_command=>"start", :stop_command=>"stop", :restart_command=>"-w 45 restart", :status_command=>"status", :options=>{:log_directory=>"/var/log/graylog2/server", :install_directory=>"/opt/graylog2", :directory=>nil, :only_if=>false, :finish_script=>false, :control=>["t"], :run_restart=>false, :active_directory=>nil, :init_script_template=>nil, :owner=>"root", :group=>"root", :template_name=>nil, :start_command=>"start", :stop_command=>"stop", :restart_command=>"-w 45 restart", :status_command=>"status", :options=>{}, :log_options=>{}, :env=>{}, :action=>:enable, :down=>false}, :log_options=>{"svlogd_size"=>209715200, "svlogd_num"=>30, "svlogd_timeout"=>86400, "svlogd_filter"=>"gzip", "svlogd_udp"=>nil, "svlogd_prefix"=>nil, "udp_log_shipping_host"=>nil, "udp_log_shipping_port"=>514, "enable"=>true, "log_directory"=>"/var/log/graylog2/server", "data_directory"=>"/var/opt/graylog2/data/spool", "node_id"=>"/var/opt/graylog2/graylog2-server-node-id", "wrapper"=>"/opt/graylog2/embedded/bin/authbind"}, :env=>{}, :action=>:enable, :down=>false, :name=>"graylog2-server"}
      provider Chef::Provider::Service::Simple
      action [:nothing]
      supports {:restart=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "graylog2-server"
      pattern "graylog2-server"
      start_command "/opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv start /opt/graylog2/service/graylog2-server"
      stop_command "/opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv stop /opt/graylog2/service/graylog2-server"
      status_command "/opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv status /opt/graylog2/service/graylog2-server"
      restart_command "/opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv -w 45 restart /opt/graylog2/service/graylog2-server"
      declared_type :service
      cookbook_name :graylog2
      recipe_name "graylog2-server"
    end
```

**Comment by mariussturm** [comment]
This issue was fixed here: https://github.com/Graylog2/graylog2-images/issues/15

**Comment by baldzern4** [comment]
With the new AMI it still isn't installing:

I get this error:

```
Recipe: graylog2::graylog2-server
  * service[graylog2-server] action restart
    
    ================================================================================
    Error executing action `restart` on resource 'service[graylog2-server]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv -w 45 restart /opt/graylog2/service/graylog2-server ----
    STDOUT: timeout: run: /opt/graylog2/service/graylog2-server: (pid 1722) 68s
    STDERR: 
    ---- End output of /opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv -w 45 restart /opt/graylog2/service/graylog2-server ----
    Ran /opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv -w 45 restart /opt/graylog2/service/graylog2-server returned 1
    
    Resource Declaration:
    ---------------------
    # In /opt/graylog2/embedded/cookbooks/runit/definitions/runit_service.rb
    
    190:     service params[:name] do
    191:       control_cmd = node[:runit][:sv_bin]
    192:       if params[:owner]
    193:         control_cmd = "#{node[:runit][:chpst_bin]} -u #{params[:owner]} #{control_cmd}"
    194:       end
    195:       provider Chef::Provider::Service::Simple
    
    Compiled Resource:
    ------------------
    # Declared in /opt/graylog2/embedded/cookbooks/runit/definitions/runit_service.rb:190:in `block in from_file'
    
    service("graylog2-server") do
      params {:directory=>"/opt/graylog2/sv", :only_if=>false, :finish_script=>false, :control=>["t"], :run_restart=>false, :active_directory=>"/opt/graylog2/service", :init_script_template=>nil, :owner=>"root", :group=>"root", :template_name=>"graylog2-server", :start_command=>"start", :stop_command=>"stop", :restart_command=>"-w 45 restart", :status_command=>"status", :options=>{:log_directory=>"/var/log/graylog2/server", :install_directory=>"/opt/graylog2", :directory=>nil, :only_if=>false, :finish_script=>false, :control=>["t"], :run_restart=>false, :active_directory=>nil, :init_script_template=>nil, :owner=>"root", :group=>"root", :template_name=>nil, :start_command=>"start", :stop_command=>"stop", :restart_command=>"-w 45 restart", :status_command=>"status", :options=>{}, :log_options=>{}, :env=>{}, :action=>:enable, :down=>false}, :log_options=>{"svlogd_size"=>209715200, "svlogd_num"=>30, "svlogd_timeout"=>86400, "svlogd_filter"=>"gzip", "svlogd_udp"=>nil, "svlogd_prefix"=>nil, "udp_log_shipping_host"=>nil, "udp_log_shipping_port"=>514, "enable"=>true, "log_directory"=>"/var/log/graylog2/server", "data_directory"=>"/var/opt/graylog2/data/spool", "node_id"=>"/var/opt/graylog2/graylog2-server-node-id", "wrapper"=>"/opt/graylog2/embedded/bin/authbind"}, :env=>{}, :action=>:enable, :down=>false, :name=>"graylog2-server"}
      provider Chef::Provider::Service::Simple
      action [:nothing]
      supports {:restart=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "graylog2-server"
      pattern "graylog2-server"
      start_command "/opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv start /opt/graylog2/service/graylog2-server"
      stop_command "/opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv stop /opt/graylog2/service/graylog2-server"
      status_command "/opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv status /opt/graylog2/service/graylog2-server"
      restart_command "/opt/graylog2/embedded/bin/chpst -u root /opt/graylog2/embedded/bin/sv -w 45 restart /opt/graylog2/service/graylog2-server"
      declared_type :service
      cookbook_name :graylog2
      recipe_name "graylog2-server"
    end
    
  * ruby_block[reload graylog2-server svlogd configuration] action create
```

**Comment by mariussturm** [comment]
Could you please rerun the `graylog2-ctl reconfigure` command, for some reasons the graylog2-server component couldn't started in time. I will create a seperated issue for that here: https://github.com/Graylog2/graylog2-images/issues/18
